#!/bin/sh

#SBATCH --job-name=ds002643-mriqc
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds002643-mriqc/.reproman/jobs/local/20230426-014248-6cb7/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds002643-mriqc/.reproman/jobs/local/20230426-014248-6cb7/stderr

#SBATCH --nodes=16
#SBATCH --ntasks=80
#SBATCH --time=8:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds002643-mriqc/.reproman/jobs/local/20230426-014248-6cb7

module load launcher
module load remora
module load ooops
set_io_param_batch $SLURM_JOBID 0 low
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 79); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun